package com.ruru.plastic.user.dao;

import com.ruru.plastic.user.model.BlueCert;
import com.ruru.plastic.user.model.BlueCertExample;

import java.util.List;

import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface BlueCertMapper {
    int countByExample(BlueCertExample example);

    int deleteByExample(BlueCertExample example);

    int deleteByPrimaryKey(Long id);

    int insert(BlueCert record);

    @Options(useGeneratedKeys = true)
    int insertSelective(BlueCert record);

    List<BlueCert> selectByExample(BlueCertExample example);

    BlueCert selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") BlueCert record, @Param("example") BlueCertExample example);

    int updateByExample(@Param("record") BlueCert record, @Param("example") BlueCertExample example);

    int updateByPrimaryKeySelective(BlueCert record);

    int updateByPrimaryKey(BlueCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blue_cert
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BlueCert selectOneByExample(BlueCertExample example);
}