package com.ruru.plastic.user.dao;

import com.ruru.plastic.user.model.CorporateCert;
import com.ruru.plastic.user.model.CorporateCertExample;

import java.util.List;

import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CorporateCertMapper {
    int countByExample(CorporateCertExample example);

    int deleteByExample(CorporateCertExample example);

    int deleteByPrimaryKey(Long id);

    int insert(CorporateCert record);

    @Options(useGeneratedKeys = true)
    int insertSelective(CorporateCert record);

    List<CorporateCert> selectByExample(CorporateCertExample example);

    CorporateCert selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") CorporateCert record, @Param("example") CorporateCertExample example);

    int updateByExample(@Param("record") CorporateCert record, @Param("example") CorporateCertExample example);

    int updateByPrimaryKeySelective(CorporateCert record);

    int updateByPrimaryKey(CorporateCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table corporate_cert
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CorporateCert selectOneByExample(CorporateCertExample example);
}