package com.ruru.plastic.user.dao;

import com.ruru.plastic.user.model.MemberLog;
import com.ruru.plastic.user.model.MemberLogExample;

import java.util.List;

import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface MemberLogMapper {
    int countByExample(MemberLogExample example);

    int deleteByExample(MemberLogExample example);

    int deleteByPrimaryKey(Long id);

    int insert(MemberLog record);

    @Options(useGeneratedKeys = true)
    int insertSelective(MemberLog record);

    List<MemberLog> selectByExample(MemberLogExample example);

    MemberLog selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") MemberLog record, @Param("example") MemberLogExample example);

    int updateByExample(@Param("record") MemberLog record, @Param("example") MemberLogExample example);

    int updateByPrimaryKeySelective(MemberLog record);

    int updateByPrimaryKey(MemberLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MemberLog selectOneByExample(MemberLogExample example);
}