package com.ruru.plastic.user.dao;

import com.ruru.plastic.user.model.PersonalCert;
import com.ruru.plastic.user.model.PersonalCertExample;

import java.util.List;

import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface PersonalCertMapper {
    int countByExample(PersonalCertExample example);

    int deleteByExample(PersonalCertExample example);

    int deleteByPrimaryKey(Long id);

    int insert(PersonalCert record);

    @Options(useGeneratedKeys = true)
    int insertSelective(PersonalCert record);

    List<PersonalCert> selectByExample(PersonalCertExample example);

    PersonalCert selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") PersonalCert record, @Param("example") PersonalCertExample example);

    int updateByExample(@Param("record") PersonalCert record, @Param("example") PersonalCertExample example);

    int updateByPrimaryKeySelective(PersonalCert record);

    int updateByPrimaryKey(PersonalCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_cert
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PersonalCert selectOneByExample(PersonalCertExample example);
}