package com.ruru.plastic.user.dao;

import com.ruru.plastic.user.model.ThirdParty;
import com.ruru.plastic.user.model.ThirdPartyExample;

import java.util.List;

import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ThirdPartyMapper {
    int countByExample(ThirdPartyExample example);

    int deleteByExample(ThirdPartyExample example);

    int deleteByPrimaryKey(Long id);

    int insert(ThirdParty record);

    @Options(useGeneratedKeys = true)
    int insertSelective(ThirdParty record);

    List<ThirdParty> selectByExample(ThirdPartyExample example);

    ThirdParty selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") ThirdParty record, @Param("example") ThirdPartyExample example);

    int updateByExample(@Param("record") ThirdParty record, @Param("example") ThirdPartyExample example);

    int updateByPrimaryKeySelective(ThirdParty record);

    int updateByPrimaryKey(ThirdParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_party
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ThirdParty selectOneByExample(ThirdPartyExample example);
}