package com.ruru.plastic.user.dao;

import com.ruru.plastic.user.model.UserMatch;
import com.ruru.plastic.user.model.UserMatchExample;

import java.util.List;

import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserMatchMapper {
    int countByExample(UserMatchExample example);

    int deleteByExample(UserMatchExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UserMatch record);

    @Options(useGeneratedKeys = true)
    int insertSelective(UserMatch record);

    List<UserMatch> selectByExample(UserMatchExample example);

    UserMatch selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UserMatch record, @Param("example") UserMatchExample example);

    int updateByExample(@Param("record") UserMatch record, @Param("example") UserMatchExample example);

    int updateByPrimaryKeySelective(UserMatch record);

    int updateByPrimaryKey(UserMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_match
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserMatch selectOneByExample(UserMatchExample example);
}