package com.ruru.plastic.user.dao;

import com.ruru.plastic.user.model.UserAccountLog;
import com.ruru.plastic.user.model.UserAccountLogExample;

import java.util.List;

import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserAccountLogMapper {
    int countByExample(UserAccountLogExample example);

    int deleteByExample(UserAccountLogExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UserAccountLog record);

    @Options(useGeneratedKeys = true)
    int insertSelective(UserAccountLog record);

    List<UserAccountLog> selectByExample(UserAccountLogExample example);

    UserAccountLog selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UserAccountLog record, @Param("example") UserAccountLogExample example);

    int updateByExample(@Param("record") UserAccountLog record, @Param("example") UserAccountLogExample example);

    int updateByPrimaryKeySelective(UserAccountLog record);

    int updateByPrimaryKey(UserAccountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserAccountLog selectOneByExample(UserAccountLogExample example);
}