package com.ruru.plastic.user.dao;

import com.ruru.plastic.user.model.UserWx;
import com.ruru.plastic.user.model.UserWxExample;

import java.util.List;

import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserWxMapper {
    int countByExample(UserWxExample example);

    int deleteByExample(UserWxExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UserWx record);

    @Options(useGeneratedKeys = true)
    int insertSelective(UserWx record);

    List<UserWx> selectByExample(UserWxExample example);

    UserWx selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UserWx record, @Param("example") UserWxExample example);

    int updateByExample(@Param("record") UserWx record, @Param("example") UserWxExample example);

    int updateByPrimaryKeySelective(UserWx record);

    int updateByPrimaryKey(UserWx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wx
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserWx selectOneByExample(UserWxExample example);
}