package com.ruru.plastic.user.dao;

import com.ruru.plastic.user.model.UserChannel;
import com.ruru.plastic.user.model.UserChannelExample;

import java.util.List;

import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserChannelMapper {
    int countByExample(UserChannelExample example);

    int deleteByExample(UserChannelExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UserChannel record);

    @Options(useGeneratedKeys = true)
    int insertSelective(UserChannel record);

    List<UserChannel> selectByExample(UserChannelExample example);

    UserChannel selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") UserChannel record, @Param("example") UserChannelExample example);

    int updateByExample(@Param("record") UserChannel record, @Param("example") UserChannelExample example);

    int updateByPrimaryKeySelective(UserChannel record);

    int updateByPrimaryKey(UserChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_channel
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserChannel selectOneByExample(UserChannelExample example);
}